### ISSUE TITLE
Does this work suit for solid lidar sensor for slam, which its fov is small ?

### ISSUE THREAD

**Issue by narutojxl** [ctu-mrs/RMS#2]
Dear authors,
Thanks for sharing this excellent work to community. When i tested our work with a solid lidar sensor for slam, its horizon fov is 120 degree, vertical fov is 60 degree. The result is not very good when compared with pcl voxel filter method, our method output filtered point cloud size is 6k, pcl voxel output point cloud size is 0.6~1.5k.
My question is:  Does our method suitable for solid lidar sensor?  Thanks for your help and time!

**Comment by petrapa6** [comment]
Hey, honestly, I haven't tested with solid-state LiDARs (don't have any in my lab) and focused on rotating ones only. I'd expect it to work but [tuning](https://github.com/ctu-mrs/RMS/blob/master/config/default.yaml) for your use case will definitely be needed.

**Comment by petrapa6** [comment]
And just an info. Voxelization (e.g., PCL voxel filter) and RMS are not expected to output the same kind (and number) of data.

**Comment by narutojxl** [comment]
Thanks author so quick reply! Currently my params value are: lambda: 0.001, voxelization.input = voxelization.output = 0.01, i need to read the paper carefully and fully understand the physical meaning of parameters lambda.  Thanks again!

**Comment by petrapa6** [comment]
Try to play with both lambda and voxel sizes. I recommend reading Sec V.B on how I did the param search. Good luck with your project!

**Comment by narutojxl** [comment]
use lambda: 0.008,  0.006, 0.004, with voxelization: input:  0.1 can have a great result, corresponding result points num is 200, 280, 380.
