### ISSUE TITLE
 performance in degenerate environment

### ISSUE THREAD

**Issue by narutojxl** [ctu-mrs/RMS#3]
Dear authors,
I carefully read our paper and code, and understand RMS outputs the points satisfy ”GFH scores high for points lying on the borders of a surface and low for points lying inside the borders (inliers)”.  
When test algorithm fast-lio2 slam system, which uses point-to-plane metric to calculate residual. In degenerate scenarios,  such as an open outdoor area of around 100 meters, the solid lidar's measurement range is 30 meters, which is installed on the lawn mower.  I found using the filtered points, the lio's trajectory in the vertical z-direction, shows upward and downward movements, namely diverge in the z-direction become serious.  Modifying parameters does not work in this degenerate environment.  In the not degenerated environment, using the filtered points, lio traj is ok.
My question is:  Did we test RMS under degenerate environment, any advice? Thansk a lot!

**Comment by petrapa6** [comment]
Hello! Apologies for the late answer.

What you describe we call _strong_ degeneracy in the RMS paper. In this case, the RMS sampling won't save you from the effects of the degeneracy --- and no other point cloud sampling will either, AFAIK. What we've tested RMS against is _weak_ degeneracy (case where you have some constraints in your data --- something like a tree or railing on a large field) where we've shown that sampling may actually help in real-time algs like `fast-lio2`.

My advice would be to check optimization-altering methods (there's a nice overview paper on arXiv from Marco Hutter's lab this year).
